apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: demo-app-dev, namespace: argocd }
spec:
  project: default
  source: { repoURL: https://github.com/MC-io/gitops-demo.git, targetRevision: main, path: demo-app/overlays/dev }
  destination: { server: https://kubernetes.default.svc, namespace: demo-dev }
  syncPolicy: { automated: { prune: true, selfHeal: true }, syncOptions: [CreateNamespace=true] }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: demo-app-staging, namespace: argocd }
spec:
  project: default
  source: { repoURL: https://github.com/MC-io/gitops-demo.git, targetRevision: main, path: demo-app/overlays/staging }
  destination: { server: https://kubernetes.default.svc, namespace: demo-staging }
  syncPolicy: { automated: { prune: true, selfHeal: true }, syncOptions: [CreateNamespace=true] }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: demo-app-prod, namespace: argocd }
spec:
  project: default
  source: { repoURL: https://github.com/MC-io/gitops-demo.git, targetRevision: main, path: demo-app/overlays/prod }
  destination: { server: https://kubernetes.default.svc, namespace: demo-prod }
  syncPolicy: { automated: { prune: true, selfHeal: true }, syncOptions: [CreateNamespace=true] }