apiVersion: v1
kind: Secret
metadata:
  name: gitops-demo-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/MC-io/gitops-demo.git
  # For a private repo, add:
  # username: <YOUR_GH_USER>
  # password: <GITHUB_PAT>